name: Service Monitor

on:
  # Run every 5 minutes
  schedule:
    - cron: '*/5 * * * *'
  
  # Also allow manual execution
  workflow_dispatch:
  
  # Run on push for testing
  push:
    branches: [ main ]

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run service monitor
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        PROD_MONITOR_URL: ${{ secrets.PROD_MONITOR_URL }}
        STAGING_MONITOR_URL: ${{ secrets.STAGING_MONITOR_URL }}
        DEV_MONITOR_URL: ${{ secrets.DEV_MONITOR_URL }}
        # Force status report when manually triggered
        FORCE_STATUS_REPORT: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
      run: node monitor.mjs